debug: false

data_folders: ['train']
fields: ['speed', 'steer', 'shift', 'rotation']
n_perts: 0
train_chance: 0.9
delay: 0.33

patch:
  hfov: 75
  vfov: 18.75
  height: 32
  width: 128
  depth: 3
  x: 0
  y: 0.38
  z: -0.33
  pitch: 0
  yaw: 0
  roll: 0
  shift_min: -0.1
  shift_max: 0.1
  rotate_min: -5
  rotate_max: 5
