components:
  - path: "joystick/dualshock4.yaml"
  - path: "camera/OV2710_100fov_1920x1080.yaml"
    name: "camera_front"
    x: -0.21 # meters forward from front axle
    y:  0.00 # meters left from center of vehicle. Assume zero for now
    z:  0.43 # meters up from floor
    roll:   0.0 # degrees left tilt. Assume zero for now
    pitch: -28. # degrees incline
    yaw:    0.0 # degrees left turn. Assume zero for now
  - path: "imu/bno055.yaml"
    name: "imu_stalk"
  - path: "servo/micromaestro_speed_3785.yaml"
    state:
      offset_speed: 0.2 # start at a reasonable high speed
  - path: "servo/micromaestro_steer_2075.yaml"
    state:
      offset_steer: 0.0 # assume no steering bias
